name: Building Argocd Vault Plugin

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"

env:
  AVP_VERSION: 1.18.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: lipaysam
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lipaysam
          password: ${{ secrets.HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./build/argocd-vault-plugin
          file: './build/argocd-vault-plugin/Dockerfile'
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            lipaysam/argocd-vault-plugin:latest
            lipaysam/argocd-vault-plugin:${{env.AVP_VERSION}}
            registry.cn-shenzhen.aliyuncs.com/lipaysam/argocd-vault-plugin:latest
            registry.cn-shenzhen.aliyuncs.com/lipaysam/argocd-vault-plugin:${{env.AVP_VERSION}}
          cache-from: type=registry,ref=lipaysam/argocd-vault-plugin:latest
          cache-to: type=inline
