name: Building Derper

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: lipaysam
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lipaysam
          password: ${{ secrets.HUB_TOKEN }}

      - name: Get latest tailscale version
        run: |
          TAILSCALE_VERSION=$(curl -s https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r '.tag_name')
          echo "Latest tailscale version: $TAILSCALE_VERSION"
          echo TAILSCALE_VERSION=$TAILSCALE_VERSION >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./build/derper
          file: "./build/derper/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            lipaysam/derper:latest
            lipaysam/derper:${{ env.TAILSCALE_VERSION }}
            registry.cn-shenzhen.aliyuncs.com/lipaysam/derper:latest
            registry.cn-shenzhen.aliyuncs.com/lipaysam/derper:${{ env.TAILSCALE_VERSION }}
          cache-from: type=registry,ref=lipaysam/derper:latest
          cache-to: type=inline
